#!/usr/bin/env node
/* build-index.mjs — reads tools/<slug>/meta.json and writes the root index.html.
   Also stamps each tool's real gzipped size into its footer: a page cannot measure itself
   at runtime without a network request, and we do not make those. Node built-ins only. */
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
const root = dirname(dirname(fileURLToPath(import.meta.url)));
const toolsDir = join(root, "tools");
const TAGLINE = "Small, single-file, no ads, no tracking, no upload.";
const esc = (s) => String(s).replace(/[&<>"]/g,
  (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

const tools = [];
for (const slug of readdirSync(toolsDir).sort()) {
  const base = join(toolsDir, slug);
  if (!statSync(base).isDirectory()) continue;
  const meta = JSON.parse(readFileSync(join(base, "meta.json"), "utf8"));
  for (const key of ["title", "blurb", "tags", "keywords"]) {
    if (!(key in meta)) throw new Error(`tools/${slug}/meta.json is missing "${key}"`);
  }
  const page = join(base, "index.html");
  let html = readFileSync(page, "utf8"), size = "";
  for (let i = 0; i < 5; i++) {                 // stamping changes the size, so settle it
    const next = (gzipSync(Buffer.from(html), { level: 9 }).length / 1024).toFixed(1) + " KB";
    if (next === size) break;
    size = next;
    html = html.replace(/(<span data-gz>)[^<]*(<\/span>)/, `$1${size}$2`);
  }
  writeFileSync(page, html);
  tools.push({ slug, size, ...meta });
}
const cards = tools.map((t) => `    <li data-k="${
  esc([t.title, t.blurb, ...t.tags, ...t.keywords].join(" ").toLowerCase())}">
      <a href="tools/${esc(t.slug)}/">
        <div class="t">${esc(t.title)}</div>
        <div class="b">${esc(t.blurb)}</div>
        <div class="g">${esc(t.tags.join(" · "))} — ${esc(t.size)}</div>
      </a>
    </li>`).join("\n");
writeFileSync(join(root, "index.html"), `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>tools</title>
<meta name="description" content="${esc(TAGLINE)} Small web utilities that run entirely in your browser.">
<link rel="stylesheet" href="shared/base.css">
<script src="shared/shell.js"></script>
</head>
<body>
<header class="topbar">
  <div class="crumb">tools</div>
  <div class="spacer"></div>
  <div class="tagline">${esc(TAGLINE)}</div>
</header>
<main>
  <p class="lede">Common web utilities, rebuilt small. Each one is a single HTML file that runs in
    this tab: no ads, no trackers, no third-party requests, nothing uploaded. Save any of them to
    disk and they keep working offline.</p>
  <div style="margin:18px 0 10px">
    <label for="q">Filter</label>
    <input type="text" id="q" data-primary spellcheck="false" placeholder="qr, convert, image…"
      aria-describedby="count">
    <p class="note" id="count" aria-live="polite" style="margin:6px 0 0"></p>
  </div>
  <ul class="tools" id="list">
${cards}
  </ul>
</main>
<footer class="foot">
  <span>${tools.length} tool${tools.length === 1 ? "" : "s"} · generated by scripts/build-index.mjs</span>
  <span class="spacer"></span>
  <button type="button" id="theme" hidden>theme</button>
  <a href="https://github.com/funkekaiser/tools">source</a>
</footer>
<script>
(function () {
  var q = document.getElementById("q"), count = document.getElementById("count");
  var items = Array.prototype.slice.call(document.querySelectorAll("#list li"));
  function run() {
    var v = q.value.trim().toLowerCase(), shown = 0;
    items.forEach(function (li) {
      var hit = !v || li.getAttribute("data-k").indexOf(v) > -1;
      li.hidden = !hit;
      if (hit) shown++;
    });
    count.textContent = shown === items.length
      ? items.length + (items.length === 1 ? " tool" : " tools") : shown + " of " + items.length;
  }
  q.addEventListener("input", run);
  run();
})();
</script>
</body>
</html>
`);
console.log(`index.html: ${tools.length} tool(s) — ${tools.map((t) => `${t.slug} ${t.size}`).join(", ")}`);
